graphhopper:
  datareader.file: data/czech-republic-latest.osm.pbf
  graph.location: data/default-gh
  elevation: true
  elevation.provider: srtm
  ghstorage.elevation: true
  graph.encoded_values: surface,track_type

profiles:
  - name: car
    vehicle: car
    weighting: fastest
