graphhopper:
  datareader.file: /data/czech-republic-latest.osm.pbf
  graph.location: /data/default-gh

  profiles:
    - name: car
      custom_model_files: [car.json]

  profiles_ch:
    - profile: car

  profiles_lm: []

  graph.encoded_values: car_access, car_average_speed, road_access

  graph.elevation.provider: srtm
  graph.elevation.cache_dir: /data/srtm

  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

  routing.snap_preventions_default: tunnel, bridge, ferry
  routing.non_ch.max_waypoint_distance: 1000000

  import.osm.ignored_highways: footway,construction,cycleway,path,steps
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
      max_request_header_size: 50k
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990

logging:
  appenders:
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
